version: '3'

services:
  local-db:
    image: library/mysql:5.7
    container_name: ${MYSQL_DB}
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${MYSQL_TZ}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_CUSTOM_CONFIG_PATH}:/etc/mysql/conf.d
      - ${MYSQL_INIT}:/docker-entrypoint-initdb.d
    platform: linux/x86_64
